version: "3.4"

services:
  kali:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    user: kali
    volumes:
      - ./start.sh:/start.sh:ro
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /mnt/hdd/shared/hacking:/hacking
      - ${HOME}/.config/zsh/.zshrc:/home/kali/.config/zsh/.zshrc:ro
      - ${HOME}/.config/bash/bashrc:/home/kali/.config/bash/bashrc:ro
      - ${HOME}/.config/aliasrc:/home/kali/.config/aliasrc:ro
      - ${HOME}/.config/envrc:/home/kali/.config/envrc:ro
      - ${HOME}/.profile:/home/kali/.profile:ro
      - ${HOME}/.config/ranger/rc.conf:/home/kali/.config/ranger/rc.conf:ro
      - ${HOME}/.config/vim/init.vim:/home/kali/.config/vim/init.vim:ro
      # - ./kali-db:/var/lib/postgres #TODO
    tty: true
    stdin_open: true
    privileged: true
    hostname: kali-docker
    container_name: kali_docker
    environment:
      - DISPLAY
