version: "3"

services:
  kali:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./kali-root:/root
      - /tmp/.X11-unix:/tmp/.X11-unix
      # - ./kali-db:/var/lib/postgres #TODO
    ports:
      - "8880:80"
    tty: true
    stdin_open: true
    privileged: true
    hostname: kali-docker
    environment:
      - DISPLAY
