version: "3.4"

services:
  kali:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    user: kali
    volumes:
      - ./start.sh:/start.sh:ro
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./default-config/alias:/etc/zsh/zshrc.d/900-alias:ro
      - ./default-config/userstartup.sh:/etc/zsh/zshrc.d/999-startup:ro # last thing that will be executed
      - ./default-config/files.txt:/home/kali/.config/files.txt:ro
      - ./default-config/commands.txt:/home/kali/.config/commands.txt:ro
      # Put your rc in /etc/zsh/zshrc.d to source them automaticly; see override file
    tty: true
    stdin_open: true
    privileged: true
    hostname: kali-docker
    container_name: kali-docker
    environment:
      - DISPLAY
      - FAKETIME="+1h"
      #- LD_PRELOAD=/usr/local/lib/faketime/libfaketime.so.1 # this breaks to many stuff
