version: "3.4"

services:
  kali:
    image: braunbearded/kali-docker:latest
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    user: kali
    volumes:
      - ./start.sh:/start.sh:ro
      - /tmp/.X11-unix:/tmp/.X11-unix
      # Put your rc in /etc/zsh/zshrc.d to source them automaticly; see override file
    tty: true
    stdin_open: true
    privileged: true
    hostname: kali-docker
    container_name: kali-docker
    extra_hosts:
      - "kali-docker:127.0.0.1"
    environment:
      - DISPLAY
      - FAKETIME="+1h"
      #- LD_PRELOAD=/usr/local/lib/faketime/libfaketime.so.1 # this breaks to many stuff
