version: "3"

services:
  kali:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./kali-root:/root
      - ./kali-db:/var/lib/postgresql/data
    ports:
      - "8880:80"
    tty: true